---
title: "w241 Final Project Analysis with Extreme Error Bounds"
output: html_notebook
---

```{r}
library('data.table')
library('readr')
library('ggplot2')
library('readxl')
library('tidyverse')
library('sandwich')
library('lmtest')
library('stargazer')
robust_se <- function(mod, type = 'HC3') { 
  sqrt(diag(vcovHC(mod, type)))
  }
```

```{r}
# read in data files
treatment_initial <- read_excel('groupA_initial.xlsx')
control_initial <- read_excel("groupB_initial.xlsx")
treatment_final <- read_excel('groupA_final.xlsx')
control_final <- read_excel("groupB_final.xlsx")

```



```{r}
# dropping and renaming columns

clean_initial_data <- function(data, treatment = FALSE) {
  
  # dropping first, extra row
  names(data) <- as.matrix(data[1, ])
  data <- data[-1, ]
  data[] <- lapply(data, function(x) type.convert(as.character(x)))
  
  # dropping and renaming columns for CONTROL GROUP
  if (treatment == FALSE) {
    data <- data[,-c(1:2)]
    data <- data[,-c(10:19)]
    data <- data[,-c(11)]
    data <- data.table(data)
    new <- c('date', 'first_name', 'last_name', 'age', 'country', 'social_apps', 'iphone', 'screen_time_rep', 'screen_time_on', 'screen_time_avg_initial')
    setnames(data,colnames(data),new)}
  
  # dropping and renaming columns for TREATMENT GROUP
  else {
    # dropping columns
    data <- data[,-c(1:7)]
    data<- data[,-c(2:10)]
    data <- data[,-c(10:19)]
    data <- data[,-c(12)]
    data <- data.table(data)
    new <- c('date', 'first_name', 'last_name', 'age', 'country', 'social_apps', 'iphone', 'greyscale', 'screen_time_rep', 'screen_time_on', 'screen_time_avg_initial')
    setnames(data,colnames(data),new)
  }
  
  # get rid of rows with empty values for name (indicates a faulty response)
  complete_vec <- complete.cases(data[, 'first_name'])
  data <- data[complete_vec,]
  
  # makes iphone column binary (iphone = 1, android = 0)
  #data$iphone <- as.numeric(data$iphone == 'IPhone')
  
  # standardizing 'United States' label
  data$country <- ifelse((data$country == 'Mexico')|(data$country == 'MX')|(data$country == 'Mx')|(data$country == 'mexico')|(data$country == 'México'),             'Mexico', 'United States' )
  # convert date to readable type
  data$date <- as.Date(data$date, origin = "1899-12-30")
  
  # create a variable to indicate which group (first cohort or second) based on date
  data[,first_group := (as.numeric(as.Date(data$date, origin = "1899-12-30") < "2021-03-23"))]
  
  return(data)
}
```

```{r}
# dropping and renaming columns 

clean_final_data <- function(data, treatment = FALSE) {
  
  # dropping first, extra row
  names(data) <- as.matrix(data[1, ])
  data <- data[-1, ]
  data[] <- lapply(data, function(x) type.convert(as.character(x)))
  
  # dropping columns
  data <- data[,-c(1:7)]
  data <- data[,-c(2:10)]
  data <-data[,-c(5:28)]
  
  # dropping and renaming columns for CONTROL GROUP
  if (treatment == FALSE) {
    data <- data[,-c(8)]
    data <- data.table(data)
    new <- c('date', 'first_name', 'last_name', 'iphone', 'screen_time_1', 'screen_time_2', 'screen_time_3')
    setnames(data,colnames(data),new)}
  
  # dropping and renaming columns for TREATMENT GROUP
  else {
    # dropping columns
    data <- data.table(data)
    new <- c('date', 'first_name', 'last_name', 'iphone', 'screen_time_1', 'screen_time_2', 'screen_time_3')
    setnames(data,colnames(data),new)
  }
  
  # get rid of rows with empty values for name (indicates a faulty response)
  complete_vec <- complete.cases(data[, 'first_name'])
  data <- data[complete_vec,]
  
  # makes iphone column binary (iphone = 1, android = 0)
  #data[, iphone_binary := ifelse(iphone == 'IPhone', 1, 0)] #$iphone <- as.numeric(data$iphone == 'IPhone')
  #data[is.na(iphone_binary), iphone_binary:=0]
  # averages screen time 
  data[, screen_time_avg_final := (rowMeans(data[,c('screen_time_1', 'screen_time_2', 'screen_time_3')]))]
  
  # convert date to readable type
  data$date <- as.Date(data$date, origin = "1899-12-30")
  
  # create a variable to indicate which group (first cohort or second) based on date
  data[,first_group := (as.numeric(as.Date(data$date, origin = "1899-12-30") < "2021-03-26"))]
  
  return(data)
}
```

```{r}
treatment_initial <- clean_initial_data(treatment_initial, treatment = TRUE)
control_initial <- clean_initial_data(control_initial, treatment = FALSE)
treatment_final <- clean_final_data(treatment_final, treatment = TRUE)
control_final <- clean_final_data(control_final, treatment = FALSE)
```



```{r}
head(treatment_initial)
head(treatment_final)
head(control_initial)
head(control_final)
```
```{r}
#group into full treatment and control group. Including people who attrited
treatment_with_attrition <- merge(treatment_initial, treatment_final[,c('first_name','screen_time_avg_final')], 
                   by.x = "first_name", by.y = "first_name", all.x = TRUE, all.y = FALSE)
control_with_attrition <- merge(control_initial, control_final[,c('first_name','screen_time_avg_final')], by.x = "first_name", by.y = "first_name", all.x = TRUE, all.y = FALSE)

#replaces NA with 0
treatment[treatment == 0] <- NA
control[control == 0] <- NA

# creating treatment column
treatment$treatment <- 1
control$treatment <- 0

#bind to make full set with attrition
data_attrition <- rbind(treatment,control, fill=TRUE)
# Drop people who were neither in innitial nor final
data_attrition <- data_attrition[!with(data_attrition,is.na(screen_time_avg_initial)& is.na(screen_time_avg_final)),]
data_attrition[, iphone_binary := ifelse(iphone == 'IPhone', 1, 0)]
data_attrition[is.na(iphone_binary), iphone_binary:=0]
head(data_attrition)
```
## Ignore attrition
```{r}
mod_nonrandom_attrition_1 <- data_attrition[, lm(screen_time_avg_final~ treatment+ screen_time_avg_initial + as.factor(country) + iphone_binary)]
```





## Create low value band
```{r}
small_screen_time <- data_attrition[, min(screen_time_avg_final, na.rm = TRUE)]

data_attrition[, low_screen_time := screen_time_avg_final]

data_attrition[is.na(low_screen_time), low_screen_time := small_screen_time]


mod_nonrandom_attrition_low <- data_attrition[ , lm(low_screen_time ~ treatment+ screen_time_avg_initial + as.factor(country) + iphone_binary)]
#summary(mod_nonrandom_attrition_low)
#mod_nonrandom_attrition_low$vcovCL_val <- vcovCL(mod_nonrandom_attrition_low)
#mod_nonrandom_attrition_low_test <- coeftest(x = mod_nonrandom_attrition_low, level = 0.95, vcov. = mod_nonrandom_attrition_low$vcovCL_val)
#mod_nonrandom_attrition_low_test

```
#No use high value band
```{r}
large_screen <- data_attrition[ , max(screen_time_avg_final, na.rm = TRUE)]

data_attrition[ , high_screen_time := screen_time_avg_final]
data_attrition[is.na(high_screen_time), high_screen_time := large_screen]

mod_nonrandom_attrition_high <- data_attrition[ , lm(high_screen_time ~ treatment+ screen_time_avg_initial + as.factor(country) + iphone_binary)]
#summary(mod_nonrandom_attrition_high)
```

## Use Mean
```{r}
mean_screen <- data_attrition[ , mean(screen_time_avg_final, na.rm = TRUE)]

data_attrition[ , mean_screen_time := screen_time_avg_final]
data_attrition[is.na(mean_screen_time), mean_screen_time := mean_screen]
mean_attrition <- data_attrition[, lm(mean_screen_time ~ treatment+ screen_time_avg_initial + as.factor(country) + iphone_binary)]
```

## Table of extreme value bands
```{r}
stargazer(
  mod_nonrandom_attrition_1, 
  mod_nonrandom_attrition_low, 
  mod_nonrandom_attrition_high,
  mean_attrition,
  type = 'text', 
  se = list(
    robust_se(mod_fully_observed_1), 
    robust_se(mod_nonrandom_attrition_1),
    robust_se(mod_nonrandom_attrition_low),
    robust_se(mod_nonrandom_attrition_high),
    robust_se(mean_attrition)
  ), 
  omit.stat = c('ser', 'F')
)
```



















